version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    command: pm2-runtime process.yml
  postgres:
    image: postgres:9.6.10-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
